config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root    'static_pages#home'
  get     '/help',     to:  'static_pages#help'
  get     '/about',    to:  'static_pages#about'
  get     '/contact',  to:  'static_pages#contact'
  get     '/signup',   to:  'users#new'
  get     '/users',    to:  'users#index'
  get     '/login',    to:  'sessions#new'
  post    '/login',    to:  'sessions#create'
  delete  '/logout',   to:  'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  before_save{ self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  private
    def downcase_email
      self.email.downcase!
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy


  def index
    @users = User.paginate(page: params[:page])
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id ])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email activate your account"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # successful edi
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation )
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "You must be logged in to access that page."
        # puts "[users_controller.rb: logged_in_user ]  login_url #{login_url} \n\n"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end


end

app/helpers/users_helper.rb
module UsersHelper

  # def gravatar_for(user, options={size: 80})
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class:"gravatar")
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user%>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <% if !logged_in? %>
    <%= f.label :password_confirmation, "Confirmaton" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  <% end %>
  <%= f.submit "create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li class="user_link">
  <div class="row">
    <div class="col-md-1">
      <%= gravatar_for user, size: 90 %>
    </div>
    <div class="col-md-11">
      <a href="<%= user_path(user) %>"><%= user.name %></a><br>
      <span>email: <%= user.email %></span>
      <% if current_user.admin? && !current_user?(user) %>
        <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  </div>
</li>
<hr>

app/views/users/edit.html.erb
<%= provide(:title, "Edit User")%>
<%# <% if logged_in? %> %>
<h1>Update Your Profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offest-3">
      <%= render 'users/form.html.erb' %>
     <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" rel="noopener" target="_blank">change</a>
    </div>`
  </div>
</div>
<%# <% else %> %>
<!-- <div class="row">
  <div class="col-md-6 col-md-offset-3">
      <h1>You must be logged in!</h1>
      <a href="/login" class="btn btn-primary">login</a>
  </div>
</div> -->
<%# <% end %> %>

app/views/users/index.html.erb
<%= provide(:title, 'Users')%>
<%= will_paginate %>

<div class="row">
  <aside class="col-md-12">
    <h1>Users List</h1>
    <ul>
      <% @users.each do |user| %>
        <%= render user  %>
      <% end %>
    </ul>
  </aside>
</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>
<p>Sign up for this app</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= render 'users/form.html.erb' %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      <%= gravatar_for @user, size:90 %>
      <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<p><%= @user.name %> <%= @user.email %></p>
<p><%= @user.created_at %> | <%= @user.updated_at %></p>
<p><%= Time.now %></p>